const data = [
  {
    images: [
      "https://m.media-amazon.com/images/I/615xmAQLTTL._AC_UL480_FMwebp_QL65_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61IXx%2B-FTXL._SL1000_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61EUo2NIKeL._SL1000_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61BwQQZ7ZwL._SL1000_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/415iWksXN9L._SL1000_.jpg",
    ],
    name: "Sundaram Artist Drawing Book",
    description: "Perfect for drawing, painting sketching",
    mrp: 175,
    price: 171,
    rating: 4.5,
    ratings: 374,
    category: "Draw & Paint",
    offers: [""],
    tags: ["Bestseller"],
    fastDelivery: false,
    inStock: true,
    freeDelivery: false,
    deliveryCharge: 45,
    amazonLink:
      "https://www.amazon.in/Sundaram-Artist-Drawing-Butter-Paper/dp/B08Q3RT1Z9/ref=sr_1_1_sspa?dchild=1&keywords=sketch+book&qid=1617886784&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFZME1USUMxN1NGQlkmZW5jcnlwdGVkSWQ9QTEwMDg1NjEyTFVLSk1KOU45T1U2JmVuY3J5cHRlZEFkSWQ9QTA1NjI4MzYyUlc0OU9XVzFVOVhKJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==",
  },
  {
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/71BeUSM6BGL._SL1280_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/81F19sTfOKL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71by-nL0HcL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71B8C2BdQxL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61yG6J8Sh0L._SL1500_.jpg",
    ],
    name: "PRINTELLIGENT Artists Sketch Book Drawing Book",
    description:
      "(100 Sheets, 200 Pages) Perforated 140 GSM Craft Book (A5 Size - Pack of 2)",
    mrp: 1100,
    price: 219,
    rating: 4.4,
    ratings: 460,
    category: "Draw & Paint",
    offers: [""],
    tags: ["Expert's Choice"],
    fastDelivery: false,
    inStock: true,
    freeDelivery: true,
    deliveryCharge: 0,
    amazonLink:
      "https://www.amazon.in/PRINTELLIGENT-Artists-Sketch-Drawing-Perforated/dp/B08R69VR3M/ref=sr_1_2_sspa?dchild=1&keywords=sketch+book&qid=1617886784&sr=8-2-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFZME1USUMxN1NGQlkmZW5jcnlwdGVkSWQ9QTEwMDg1NjEyTFVLSk1KOU45T1U2JmVuY3J5cHRlZEFkSWQ9QTA2Nzk1MzlBUkxGNkNWVjMwSk8md2lkZ2V0TmFtZT1zcF9hdGYmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl",
  },
  {
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/71J6UgzIJQL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61rTxLLrrfL._SL1017_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71boBwnDPJL._SL1323_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61OrunPocCL._SL1300_.jpg",
    ],
    name: "SYGA Professional Sketch and Drawing Pencils",
    description:
      "Art Pencil Box Contains 12 Pieces Set B 2B 3B 4B 5B 6B 7B 8B HB H 2H F",
    mrp: 550,
    price: 199,
    rating: 4.1,
    ratings: 637,
    category: "Draw & Paint",
    offers: [""],
    tags: ["Bestseller"],
    fastDelivery: true,
    inStock: true,
    freeDelivery: true,
    deliveryCharge: 0,
    amazonLink:
      "https://www.amazon.in/SYGA-Professional-Drawing-pencils-Contains/dp/B07H3MJRC9/ref=sr_1_5?crid=1WF7GHTQ1U46C&dchild=1&keywords=graphite+drawing+pencil&qid=1617910198&sprefix=graphite+dra%2Caps%2C337&sr=8-5",
  },
  {
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/5104qlpAl5L.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/51FezhbUzEL._SL1280_.jpg",
    ],
    name: "Cretacolor kneadable Eraser Big",
    description: "(Pack of 4)",
    mrp: 252,
    price: 252,
    rating: 4,
    ratings: 298,
    category: "Draw & Paint",
    offers: [""],
    tags: ["Expert's choice"],
    fastDelivery: false,
    inStock: true,
    freeDelivery: false,
    deliveryCharge: 45,
    amazonLink:
      "https://www.amazon.in/Cretacolor-kneadable-Eraser-Big-Pack/dp/B00PP6N16E/ref=sr_1_1_sspa?crid=3PGOPVLOYMXSC&dchild=1&keywords=kneaded+eraser&qid=1617912290&sprefix=knea%2Caps%2C347&sr=8-1-spons&psc=1&smid=A18WLTS0SXY58J&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFYU1hLWktQVzRSWTUmZW5jcnlwdGVkSWQ9QTA0OTg3MjMyWDFYS0hYUE9VTjczJmVuY3J5cHRlZEFkSWQ9QTEwMjgxNTkyUkZHSjdQNjhLV0FDJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==",
  },
  {
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/81W%2Bd2SozNL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71zT5Ug6gsL._SL1200_.jpg",
    ],
    name: "Camlin Kokuyo Artist 5ml Water Color Tube",
    description: "- 24 Shades (Multicolor)",
    mrp: 390,
    price: 351,
    rating: 4.5,
    ratings: 1161,
    category: "Draw & Paint",
    offers: [""],
    tags: ["Bestseller"],
    fastDelivery: false,
    inStock: true,
    freeDelivery: false,
    deliveryCharge: 45,
    amazonLink:
      "https://www.amazon.in/Camlin-Kokuyo-Artist-Water-Color/dp/B0752KW82G/ref=sr_1_6?dchild=1&keywords=watercolor+paint+set&qid=1617914946&sr=8-6",
  },
  {
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/71Xuw6Pdt2L._SL1000_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61dziLxhplL._SL1000_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/81WfDMPoaIL._SL1200_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61yTzS8llcL._SL1000_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71Q47vwtq2L._SL1200_.jpg",
    ],
    name: "Mont Marte Acrylic Paint Set 24 Colours 36ml",
    description:
      "Perfect for Canvas, Wood, Fabric, Leather, Cardboard, Paper, MDF and Crafts",
    mrp: 4999,
    price: 1750,
    rating: 4.8,
    ratings: 4696,
    category: "Draw & Paint",
    offers: [""],
    tags: ["Bestseller", "Expert's choice"],
    fastDelivery: true,
    inStock: true,
    freeDelivery: true,
    deliveryCharge: 0,
    amazonLink:
      "https://www.amazon.in/Mont-Marte-Acrylic-Colours-Cardboard/dp/B07BPPGYB1/ref=sr_1_13?crid=2H42IR2D7J8DN&dchild=1&keywords=acrylic+paint+set&qid=1617915433&sprefix=acrylic+%2Caps%2C521&sr=8-13",
  },
  {
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/71VO-yXCjHL._SL1080_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71h6-dIi6gL._SL1081_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/617Vs%2BAhkAL._SL1080_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61Mw9MtBbAL._SL1080_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61BLqlVkuOL._SL1080_.jpg",
    ],
    name: "Artist's Den Synthetic Hair Mix Brushes Set",
    description:
      "for Acrylic, Watercolor, Gouache & Oil Painting (Set of 13 Mix)",
    mrp: 850,
    price: 645,
    rating: 4.5,
    ratings: 108,
    category: "Draw & Paint",
    offers: [""],
    tags: [""],
    fastDelivery: true,
    inStock: true,
    freeDelivery: true,
    deliveryCharge: 0,
    amazonLink:
      "https://www.amazon.in/Artists-Den-Synthetic-Watercolor-Painting/dp/B08L3VJKNG/ref=sr_1_1_sspa?crid=UNMCZ78LGAZM&dchild=1&keywords=paint+brushes&qid=1617916127&sprefix=paint+brus%2Caps%2C330&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzVEEzQjlTUFFBQ09FJmVuY3J5cHRlZElkPUEwNzQ3MzU1WlU0TTBORk1ESVRVJmVuY3J5cHRlZEFkSWQ9QTAxNzY2NjRDRVExVVFHTjdDNUgmd2lkZ2V0TmFtZT1zcF9hdGYmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl",
  },
  {
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/41hjwSYfdmL.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71NbMshvKVL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71UH46aTcmL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/811MQx-tK6L._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/81WVRiPr3jL._SL1500_.jpg",
    ],
    name: "Kadence Frontier Series, Acoustic Guitar",
    description:
      "With/Wihtout EQ Die Cast Keys Combo (Bag,strap,strings and 3 picks) (Brown, Acoustic)",
    mrp: 7000,
    price: 5299,
    rating: 4,
    ratings: 526,
    category: "Music",
    offers: [""],
    tags: ["Bestseller"],
    fastDelivery: true,
    inStock: true,
    freeDelivery: true,
    deliveryCharge: 0,
    amazonLink:
      "https://www.amazon.in/Kadence-Frontier-Acoustic-Guitar-Strings/dp/B01GDZ46AA/ref=sr_1_7?dchild=1&keywords=guitar&qid=1617916528&refinements=p_72%3A1318476031&rnid=1318475031&sr=8-7",
  },
  {
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/81od6jVzz4L._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61R2bC2IvbL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/81JIKP0eY0L._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71VgbP-POPL._SL1500_.jpg",
    ],
    name: "Yamaha PSR-E-363 61",
    description: "Key Touch Sensitive Portable Keyboard",
    mrp: 12990,
    price: 11999,
    rating: 4.4,
    ratings: 1328,
    category: "Music",
    offers: [""],
    tags: ["Bestseller"],
    fastDelivery: true,
    inStock: true,
    freeDelivery: false,
    deliveryCharge: 700,
    amazonLink:
      "https://www.amazon.in/Yamaha-61-Key-Sensitive-Portable-Keyboard/dp/B06XT4N6WT/ref=sr_1_5?crid=1FRBYVBH37T03&dchild=1&keywords=piano+keyboard+for+adults&qid=1617917035&refinements=p_89%3AYAMAHA&rnid=3837712031&s=musical-instruments&sprefix=piano+%2Caps%2C358&sr=1-5",
  },
  {
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/61gccqQDLRL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61TEa%2BkbleL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61HmpW3uu5L._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/81aCJTO0hnL._SL1500_.jpg",
    ],
    name: "Clapbox Adjustable Snare Cajon CB50",
    description: "Oak Wood, (H:50 W:30 L:30) - 3 Internal Snares",
    mrp: 14500,
    price: 4499,
    rating: 4.5,
    ratings: 647,
    category: "Music",
    offers: [""],
    tags: ["Expert's choice"],
    fastDelivery: true,
    inStock: true,
    freeDelivery: true,
    deliveryCharge: 0,
    amazonLink:
      "https://www.amazon.in/Clapbox-Adjustable-Snare-Cajon-CB50/dp/B07SQC9JMG/ref=sr_1_3_sspa?dchild=1&keywords=cajon&qid=1617917235&s=musical-instruments&sr=1-3-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzNFczUlFGT0QzU1QwJmVuY3J5cHRlZElkPUEwNzE2NjExMzRNQ085RUVSSEJYNyZlbmNyeXB0ZWRBZElkPUEwODA2NjE4VjNDWkJDUlkwUFNGJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==",
  },
  {
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/61rmNczZHjL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61NCt85gmoL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/31m4WRFIQ-L.jpg",
    ],
    name: "Hetkrishi Mouth Organ",
    description: "with 24 Holes (Multi Color)",
    mrp: 399,
    price: 180,
    rating: 3,
    ratings: 20,
    category: "Music",
    offers: [""],
    tags: [""],
    fastDelivery: false,
    inStock: true,
    freeDelivery: false,
    deliveryCharge: 80,
    amazonLink:
      "https://www.amazon.in/Hetkrishi-Mouth-Organ-Holes-Multi/dp/B08JHQ4LMJ/ref=sr_1_8?crid=2VDKTYL40HLOX&dchild=1&keywords=mouth+organ&qid=1617917684&s=musical-instruments&sprefix=mouth%2Cmi%2C513&sr=1-8",
  },
  {
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/61wPFXszBHL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71uaPoCLbTL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71g7HxV5grL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71Xw5hFy93L._SL1500_.jpg",
    ],
    name: "East top Mouth Organ C Key 10 Holes 20 Tones",
    description:
      "Diatonic Harmonica Mouth Organ for Adults, Beginners, Professionals and Students with Blue Cover, T003",
    mrp: 1999,
    price: 1491,
    rating: 4.5,
    ratings: 777,
    category: "Music",
    offers: [""],
    tags: ["Bestseller"],
    fastDelivery: true,
    inStock: true,
    freeDelivery: true,
    deliveryCharge: 0,
    amazonLink:
      "https://www.amazon.in/East-top-Professional-Harmonica-Instrument/dp/B07MM1WLSV/ref=sr_1_2_sspa?crid=2VDKTYL40HLOX&dchild=1&keywords=mouth+organ&qid=1617917684&s=musical-instruments&sprefix=mouth%2Cmi%2C513&sr=1-2-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzRzFIMEQ5NVBXVTUxJmVuY3J5cHRlZElkPUEwNzUwOTg3MjlKRkxKS01SRTVIMSZlbmNyeXB0ZWRBZElkPUEwNzU4MTA1N1M1TElLVlU0S00xJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==",
  },
  {
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/61BxZy9NpQL._SL1000_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61OU46qakhL._SL1000_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61WOieynKfL._SL1000_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61BLJTdphHL._SL1000_.jpg",
    ],
    name: "Powerpak G3001A Electronic Drum Pad",
    description: "(Black/White)",
    mrp: 7000,
    price: 3771,
    rating: 4,
    ratings: 102,
    category: "Music",
    offers: [""],
    tags: [""],
    fastDelivery: true,
    inStock: true,
    freeDelivery: true,
    deliveryCharge: 0,
    amazonLink:
      "https://www.amazon.in/Powerpak-G3001A-Electronic-Drum-White/dp/B07KPF7LVT/ref=sr_1_5_mod_primary_lightning_deal?dchild=1&keywords=drums&qid=1617921947&s=musical-instruments&sbo=Tc8eqSFhUl4VwMzbE4fw%2Fw%3D%3D&smid=A14CZOWI0VEHLG&sr=1-5",
  },
  {
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/71mNT-aTizL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/6112KCZQ3gL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61GleWQ-rOL._SL1500_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/611T7g9KmRL._SL1500_.jpg",
    ],
    name: "STARDEALS C Natural 7 Hole Right Hand Bamboo Flute Bansuri",
    description: "Size 19 Inch With Free Carry Bag (Natural Brown)",
    mrp: 1299,
    price: 519,
    rating: 4,
    ratings: 63,
    category: "Music",
    offers: [""],
    tags: ["Expert's choice"],
    fastDelivery: true,
    inStock: false,
    freeDelivery: true,
    deliveryCharge: 0,
    amazonLink:
      "https://www.amazon.in/Musical-Flutes-Bamboo-Natural-Bansuri/dp/B084265N48/ref=sr_1_4?dchild=1&keywords=flute&qid=1617922267&s=musical-instruments&sr=1-4",
  },
];

module.exports = data;

// {
//     images: [
//       "",
//       "",
//       "",
//       "",
//       "",
//     ],
//     name: "",
//     description:
//       "",
//     mrp: 1,
//     price: 1,
//     rating: 4,
//     ratings: 4696,
//     category: "Draw & Paint",
//     offers: [""],
//     tags: [""],
//     fastDelivery: true,
//     inStock: true,
//     freeDelivery: true,
//     deliveryCharge: 0,
//     amazonLink: "",
// }
